const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height,q=s=>document.querySelector(s);
const ui={start:q('#start'),hero:q('#heroSelect'),weapon:q('#weaponSelect'),up:q('#levelUp'),pause:q('#pause'),over:q('#gameOver'),heroes:q('#heroes'),weapons:q('#weapons'),choices:q('#choices'),xp:q('#xp'),level:q('#level'),clock:q('#clock'),status:q('#status'),kills:q('#kills'),build:q('#build'),result:q('#result')};
const keys={};let game=null,raf=0,last=0,best=Number(localStorage.getItem('void-garden-best'))||0,audio=null;addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='p'&&!e.repeat)pause()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
const heroes=[['星芽','均衡 · 多重星弹','开局 3 枚扇形星弹，适合快速清场。','#dca6ff',p=>p.shots=3],['荆棘蔓','爆发 · 穿透荆刺','伤害与穿透更高，但施法略慢。','#ff9abf',p=>{p.damage=32;p.pierce=2;p.cd=.85}],['露珠','生存 · 磁吸花露','生命更高、吸收范围更大，并持续回复。','#8dffe0',p=>{p.max=145;p.hp=145;p.magnet=160;p.regen=1.2}]];
const weapons=[['星辉法杖','快速 · 星弹','高速星弹会自动追踪最近敌人。','#cda2ff',p=>p.weapon='star'],['蔷薇短弓','爆裂 · 花苞','命中后产生小范围爆裂伤害。','#ff8eb7',p=>{p.weapon='rose';p.splash=42;p.cd*=1.12}],['月刃轮','穿透 · 回旋','更大、更慢的月刃，擅长切开敌群。','#fff0a5',p=>{p.weapon='moon';p.pierce+=2;p.damage*=1.2;p.bulletSize=9;p.bulletSpeed=.72}]];
const upgrades=[['月光花','施法间隔 -16%',p=>p.cd=Math.max(.18,p.cd*.84)],['荆棘蔓','法术伤害 +42%',p=>p.damage*=1.42],['流星种','投射物 +1',p=>p.shots++],['碎星','投射物穿透 +1',p=>p.pierce++],['疾风草','移动速度 +14%',p=>p.speed*=1.14],['丰收','经验获得 +30%',p=>p.xpGain*=1.3],['露珠','最大生命 +24，并立刻治疗',p=>{p.max+=24;p.hp=Math.min(p.max,p.hp+24)}],['藤蔓罗盘','拾取范围 +45',p=>p.magnet+=45],['苔藓心','每秒回复 +0.7',p=>p.regen+=.7],['环月花','获得 1 枚环绕月种',p=>p.orbits++],['春雷','每 5 秒释放一次雷霆绽放',p=>p.nova=1],['夜色花粉','暴击率 +12%',p=>p.crit+=.12],['肥沃土壤','爆裂范围 +26',p=>p.splash+=26],['流光花瓣','投射物速度 +18%',p=>p.bulletSpeed*=1.18],['大朵花冠','投射物尺寸 +2',p=>p.bulletSize+=2],['月蚀','暴击伤害提高至 2.7 倍',p=>p.critDamage=2.7]];
function fresh(){return {t:0,spawn:0,cast:0,novaClock:5,nextBoss:60,level:1,xp:0,need:10,kills:0,paused:false,ended:false,evolved:false,enemies:[],bullets:[],enemyBullets:[],stars:[],effects:[],bg:Array.from({length:60},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*2+1,a:Math.random()})),p:{x:W/2,y:H/2,r:12,hp:100,max:100,speed:225,damage:18,cd:.66,shots:1,pierce:0,magnet:105,xpGain:1,regen:0,orbits:0,nova:0,crit:0,splash:0,bulletSize:5,bulletSpeed:1,name:'',weapon:''}}}
function heroesScreen(){ui.start.classList.add('hidden');ui.hero.classList.remove('hidden');ui.heroes.innerHTML='';heroes.forEach(h=>{let b=document.createElement('button');b.className='choice';b.innerHTML=`<b style="color:${h[3]}">${h[0]}</b><span>${h[1]}<br>${h[2]}</span>`;b.onclick=()=>weaponScreen(h);ui.heroes.append(b)})}
function weaponScreen(hero){ui.hero.classList.add('hidden');ui.weapon.classList.remove('hidden');ui.weapons.innerHTML='';weapons.forEach(w=>{let b=document.createElement('button');b.className='choice';b.innerHTML=`<b style="color:${w[3]}">${w[0]}</b><span>${w[1]}<br>${w[2]}</span>`;b.onclick=()=>start(hero,w);ui.weapons.append(b)})}
function start(h,w){audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();game=fresh();game.p.name=h[0];h[4](game.p);w[4](game.p);ui.weapon.classList.add('hidden');ui.over.classList.add('hidden');ui.build.textContent=`${h[0]} · ${w[0]}`;ui.status.textContent=`存活时间 · 最佳 ${best}s`;last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function spawn(type='normal'){let a=Math.random()*7,d=400,e={x:W/2+Math.cos(a)*d,y:H/2+Math.sin(a)*d,r:11,hp:28+game.t*.45,spd:56+game.t*.5,value:1,color:'#7c62bb'};if(type==='runner')e={...e,r:8,hp:16+game.t*.25,spd:116+game.t*.7,color:'#78b9dc'};if(type==='brute')e={...e,r:19,hp:105+game.t*1.1,spd:32+game.t*.22,value:4,color:'#d56cab'};if(type==='boss')e={...e,r:34,hp:440+game.t*7,max:440+game.t*7,spd:30,value:18,color:'#ef5f92',boss:true,shot:1.4};game.enemies.push(e)}
function shoot(){let p=game.p,t=[...game.enemies].sort((a,b)=>dist(p,a)-dist(p,b))[0];if(!t)return;tone(p.weapon==='moon'?290:510,.025,.025);let base=Math.atan2(t.y-p.y,t.x-p.x);for(let i=0;i<p.shots;i++){let a=base+(i-(p.shots-1)/2)*.18,s=465*p.bulletSpeed;game.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:p.weapon==='moon'?1.55:1.18,pierce:p.pierce,damage:p.damage,crit:Math.random()<p.crit,size:p.bulletSize,splash:p.splash,hits:[]})}}
function choose(){game.paused=true;ui.up.classList.remove('hidden');ui.choices.innerHTML='';shuffle(upgrades).slice(0,3).forEach(u=>{let b=document.createElement('button');b.className='choice';b.innerHTML=`<b>${u[0]}</b><span>${u[1]}</span>`;b.onclick=()=>{u[2](game.p);game.paused=false;ui.up.classList.add('hidden');ui.build.textContent=`${game.p.name} · 已培育 ${game.level-1} 次`};ui.choices.append(b)})}
function update(dt){let g=game,p=g.p;pad();g.t+=dt;g.spawn-=dt;g.cast-=dt;g.novaClock-=dt;p.hp=Math.min(p.max,p.hp+p.regen*dt);if(g.t>=g.nextBoss){spawn('boss');g.nextBoss+=60;ui.status.textContent='虚空园丁降临！';tone(145,.25,.07)}if(g.spawn<=0){let r=Math.random();spawn(g.t>35&&r>.87?'brute':g.t>15&&r>.62?'runner':'normal');g.spawn=Math.max(.15,.76-g.t*.006)}if(g.cast<=0){shoot();g.cast=p.cd}if(p.nova&&g.novaClock<=0){nova();g.novaClock=5}move(p,dt);g.enemies.forEach(e=>enemy(e,p,g,dt));orbit(p,g,dt);bullets(g,dt);enemyShots(g,p,dt);collect(g,p,dt);if(p.hp<=0)end();hud()}
function move(p,dt){let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0)+(game.padX||0)+(game.touchX||0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0)+(game.padY||0)+(game.touchY||0);if(dx||dy){let n=Math.hypot(dx,dy);p.x=clamp(p.x+dx/n*p.speed*dt,15,W-15);p.y=clamp(p.y+dy/n*p.speed*dt,15,H-15)}}
function enemy(e,p,g,dt){let a=Math.atan2(p.y-e.y,p.x-e.x),d=dist(p,e);e.x+=Math.cos(a)*e.spd*dt;e.y+=Math.sin(a)*e.spd*dt;if(d<e.r+p.r)p.hp-=(e.boss?28:e.r>15?16:8)*dt;if(e.boss&&(e.shot-=dt)<=0){e.shot=1.55;for(let i=-1;i<=1;i++){let z=a+i*.28;g.enemyBullets.push({x:e.x,y:e.y,vx:Math.cos(z)*185,vy:Math.sin(z)*185,life:3})}}}
function enemyShots(g,p,dt){g.enemyBullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(!b.hit&&dist(b,p)<p.r+7){b.hit=true;p.hp-=13;g.effects.push({x:p.x,y:p.y,life:.2,color:'#ff779e'})}});g.enemyBullets=g.enemyBullets.filter(b=>b.life>0&&!b.hit)}
function orbit(p,g,dt){for(let o=0;o<p.orbits;o++){let a=g.t*2.3+o*7/p.orbits,z={x:p.x+Math.cos(a)*48,y:p.y+Math.sin(a)*48};g.enemies.forEach(e=>{if(dist(z,e)<e.r+7)e.hp-=18*dt})}}
function bullets(g,dt){g.bullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;g.enemies.forEach(e=>{if(!b.hits.includes(e)&&dist(b,e)<e.r+b.size){b.hits.push(e);let hit=b.damage*(b.crit?(g.p.critDamage||2):1);e.hp-=hit;if(b.splash){g.enemies.forEach(other=>{if(other!==e&&dist(e,other)<b.splash)other.hp-=hit*.45});g.effects.push({x:e.x,y:e.y,life:.3,color:'#ff96c4',nova:true})}g.effects.push({x:e.x,y:e.y,life:.18,color:b.crit?'#fff2a8':'#f4caff'});b.pierce--}});});g.bullets=g.bullets.filter(b=>b.life>0&&b.pierce>=0);g.enemies=g.enemies.filter(e=>{if(e.hp>0)return true;g.kills++;g.stars.push({x:e.x,y:e.y,value:e.value});if(e.boss){g.p.hp=Math.min(g.p.max,g.p.hp+35);ui.status.textContent='园丁已被净化'}return false})}
function collect(g,p,dt){g.stars=g.stars.filter(s=>{let d=dist(p,s);if(d<18){g.xp+=s.value*p.xpGain;while(g.xp>=g.need){g.xp-=g.need;g.level++;g.need=Math.ceil(g.need*1.3);if(!g.evolved&&g.level>=6)evolve(g);choose()}return false}if(d<p.magnet){s.x+=(p.x-s.x)*dt*5;s.y+=(p.y-s.y)*dt*5}return true});g.effects=g.effects.filter(e=>(e.life-=dt)>0)}
function evolve(g){g.evolved=true;let p=g.p,name='';if(p.weapon==='star'){p.shots+=2;p.cd*=.85;name='星辉法杖 → 星群权杖'}else if(p.weapon==='rose'){p.splash+=40;p.pierce+=1;name='蔷薇短弓 → 绽放花冠'}else{p.orbits+=2;p.damage*=1.35;name='月刃轮 → 满月圣环'}g.effects.push({x:p.x,y:p.y,life:.8,color:'#fff0a5',nova:true});ui.status.textContent=`法器进化：${name}`;ui.build.textContent=`${p.name} · ${name}`;tone(720,.3,.08)}
function nova(){let p=game.p;game.effects.push({x:p.x,y:p.y,life:.42,color:'#d9b7ff',nova:true});game.enemies.forEach(e=>{let d=dist(p,e);if(d<150)e.hp-=Math.max(12,p.damage*.9)*(1-d/190)})}
function hud(){let g=game;ui.xp.style.width=`${g.xp/g.need*100}%`;ui.level.textContent=`LV. ${g.level}`;ui.kills.textContent=`净化 ${g.kills}`;let m=Math.floor(g.t/60),s=Math.floor(g.t%60);ui.clock.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function draw(){let g=game,p=g.p;ctx.clearRect(0,0,W,H);ctx.fillStyle='#101126';ctx.fillRect(0,0,W,H);g.bg.forEach(s=>{s.y=(s.y+.12)%H;ctx.globalAlpha=.18+s.a*.35;dot(s.x,s.y,s.r,'#b9a5ef')});ctx.globalAlpha=1;ctx.strokeStyle='#1c1d3a';for(let i=0;i<W;i+=40){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,H);ctx.stroke()}for(let i=0;i<H;i+=40){ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(W,i);ctx.stroke()}g.effects.forEach(e=>{ctx.globalAlpha=e.life/.42;ctx.strokeStyle=e.color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,e.nova?160*(1-e.life/.42):18,0,7);ctx.stroke();ctx.globalAlpha=1});g.stars.forEach(s=>dot(s.x,s.y,4,'#83ffd6'));g.bullets.forEach(b=>{dot(b.x,b.y,b.crit?b.size+3:b.size,b.crit?'#fff2a8':game.p.weapon==='rose'?'#ff9ac1':game.p.weapon==='moon'?'#fff0a5':'#ffd2fb');dot(b.x,b.y,2,'#fff')});g.enemyBullets.forEach(b=>dot(b.x,b.y,7,'#ff6d9f'));g.enemies.forEach(e=>{dot(e.x,e.y,e.r,e.color);dot(e.x-3,e.y-2,2,'#fbd2ff');if(e.boss){ctx.fillStyle='#2a2246';ctx.fillRect(e.x-32,e.y-e.r-11,64,5);ctx.fillStyle='#ff9fc2';ctx.fillRect(e.x-32,e.y-e.r-11,64*e.hp/e.max,5)}});for(let o=0;o<p.orbits;o++){let a=g.t*2.3+o*7/p.orbits;dot(p.x+Math.cos(a)*48,p.y+Math.sin(a)*48,7,'#fff0a5')}dot(p.x,p.y,25,'#39205c');dot(p.x,p.y,18,'#c790ff');dot(p.x-5,p.y-5,4,'#fff1ff');ctx.fillStyle='#25264d';ctx.fillRect(20,H-25,160,8);ctx.fillStyle='#ff759c';ctx.fillRect(20,H-25,160*clamp(p.hp/p.max,0,1),8);ctx.fillStyle='#e7dbf5';ctx.font='11px Space Mono';ctx.fillText(`${Math.ceil(p.hp)} / ${p.max}`,188,H-18)}
function loop(now){let dt=Math.min(.033,(now-last)/1000);last=now;if(game&&!game.paused)update(dt);if(game)draw();raf=requestAnimationFrame(loop)}function pause(){if(!game||game.ended||!ui.up.classList.contains('hidden'))return;game.paused=!game.paused;ui.pause.classList.toggle('hidden',!game.paused)}function pad(){let p=navigator.getGamepads?.()[0];game.padX=0;game.padY=0;if(!p)return;game.padX=Math.abs(p.axes[0])>.25?p.axes[0]:0;game.padY=Math.abs(p.axes[1])>.25?p.axes[1]:0;if(p.buttons[9]?.pressed&&!game.padHeld)pause();game.padHeld=!!p.buttons[9]?.pressed}function tone(freq,duration,volume){if(!audio)return;let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.value=volume;o.connect(g).connect(audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.stop(audio.currentTime+duration)}function end(){if(game.ended)return;game.ended=true;game.paused=true;tone(180,.35,.08);let seconds=Math.floor(game.t),newBest=seconds>best;if(newBest){best=seconds;localStorage.setItem('void-garden-best',best)}let medal=game.kills>=100?' · 获得「百花守望」':game.level>=8?' · 获得「茂盛花圃」':'';ui.result.textContent=`${game.p.name} 将花园培育至第 ${game.level} 阶，净化 ${game.kills} 个虚空生物，存活 ${seconds} 秒${newBest?' · 新纪录！':medal}`;ui.over.classList.remove('hidden')}function dot(x,y,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.fill()}function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function clamp(n,a,b){return Math.max(a,Math.min(b,n))}function shuffle(a){return [...a].sort(()=>Math.random()-.5)}q('#startBtn').onclick=heroesScreen;q('#againBtn').onclick=heroesScreen;q('#resumeBtn').onclick=pause;
